var resources = 
{
    "en": {
        "translation": {
            "&#10;&#10;": "&#10;&#10;", 
            "&gt;": "&gt;", 
            "&lt;": "&lt;", 
            "+": "+", 
            "+/-20_V": "+/-20 V", 
            "+1.2V": "+1.2V", 
            "+1.5V": "+1.5V", 
            "+1.8V": "+1.8V", 
            "+12V": "+12V", 
            "+20_V": "+20 V", 
            "+3.3V": "+3.3V", 
            "+5V": "+5V", 
            "-": "-", 
            "-12V": "-12V", 
            "-20_V": "-20 V", 
            ".": ".", 
            "1": "1", 
            "10": "10", 
            "100": "100", 
            "1000": "1000", 
            "1001": "1001", 
            "101": "101", 
            "1010": "1010", 
            "1011": "1011", 
            "11": "11", 
            "110": "110", 
            "1100": "1100", 
            "1101": "1101", 
            "111": "111", 
            "1110": "1110", 
            "1111": "1111", 
            "12": "12", 
            "13": "13", 
            "14": "14", 
            "15": "15", 
            "16": "16", 
            "17": "17", 
            "18": "18", 
            "19": "19", 
            "2": "2", 
            "20": "20", 
            "21": "21", 
            "22": "22", 
            "23": "23", 
            "24": "24", 
            "25": "25", 
            "26": "26", 
            "27": "27", 
            "28": "28", 
            "29": "29", 
            "2W": "2W", 
            "3": "3", 
            "30": "30", 
            "31": "31", 
            "32": "32", 
            "33": "33", 
            "34": "34", 
            "35": "35", 
            "36": "36", 
            "37": "37", 
            "38": "38", 
            "39": "39", 
            "4": "4", 
            "40": "40", 
            "41": "41", 
            "42": "42", 
            "43": "43", 
            "44": "44", 
            "45": "45", 
            "46": "46", 
            "47": "47", 
            "48": "48", 
            "49": "49", 
            "5": "5", 
            "50": "50", 
            "51": "51", 
            "52": "52", 
            "53": "53", 
            "54": "54", 
            "55": "55", 
            "56": "56", 
            "57": "57", 
            "58": "58", 
            "59": "59", 
            "6": "6", 
            "60": "60", 
            "61": "61", 
            "62": "62", 
            "63": "63", 
            "64": "64", 
            "65": "65", 
            "66": "66", 
            "67": "67", 
            "68": "68", 
            "69": "69", 
            "7": "7", 
            "70": "70", 
            "71": "71", 
            "72": "72", 
            "73": "73", 
            "74": "74", 
            "75": "75", 
            "76": "76", 
            "77": "77", 
            "78": "78", 
            "79": "79", 
            "8": "8", 
            "80": "80", 
            "81": "81", 
            "82": "82", 
            "83": "83", 
            "84": "84", 
            "85": "85", 
            "86": "86", 
            "87": "87", 
            "88": "88", 
            "89": "89", 
            "9": "9", 
            "90": "90", 
            "91": "91", 
            "92": "92", 
            "93": "93", 
            "94": "94", 
            "95": "95", 
            "96": "96", 
            "97": "97", 
            "98": "98", 
            "99": "99", 
            "A": "A", 
            "AC": "AC", 
            "AC Analysis": "AC Analysis", 
            "AC_V": "AC V", 
            "ADC": "ADC", 
            "ARB": "ARB", 
            "Acquire": "Acquire", 
            "Amp": "Amp", 
            "Ampl": "Ampl", 
            "Analyzer": "Analyzer", 
            "Arrow": "Arrow", 
            "Auto": "Auto", 
            "Auto/": "Auto/", 
            "Avg": "Avg", 
            "B": "B", 
            "B1": "B1", 
            "B2": "B2", 
            "BW/": "BW/", 
            "C": "C", 
            "CLK": "CLK", 
            "CLR": "CLR", 
            "CONFIRM": "CONFIRM", 
            "CS": "CS", 
            "Cal": "Cal", 
            "Center": "Center", 
            "Ch_1": "Ch 1", 
            "Ch_2": "Ch 2", 
            "Ch_3": "Ch 3", 
            "Ch_4": "Ch 4", 
            "Cntl": "Cntl", 
            "Common": "Common", 
            "Cont": "Cont", 
            "Container": "Container", 
            "Couple": "Couple", 
            "Cursor": "Cursor", 
            "Cursors": "Cursors", 
            "D": "D", 
            "D0": "D0", 
            "D1": "D1", 
            "D10": "D10", 
            "D11": "D11", 
            "D12": "D12", 
            "D13": "D13", 
            "D14": "D14", 
            "D15": "D15", 
            "D2": "D2", 
            "D3": "D3", 
            "D4": "D4", 
            "D5": "D5", 
            "D6": "D6", 
            "D7": "D7", 
            "D8": "D8", 
            "D9": "D9", 
            "DAC": "DAC", 
            "DC": "DC", 
            "DC transfer characteristic": "DC transfer characteristic", 
            "DC_Supply": "DC Supply", 
            "DC_V": "DC V", 
            "DMM": "DMM", 
            "Decibel": "Decibel", 
            "Delay": "Delay", 
            "Demo": "Demo", 
            "Disp": "Disp", 
            "Display": "Display", 
            "Div_10": "Div 10", 
            "Done": "Done", 
            "Double Ellipse": "Double Ellipse", 
            "E": "E", 
            "Ellipse": "Ellipse", 
            "Entry": "Entry", 
            "Ext": "Ext", 
            "External": "External", 
            "F": "F", 
            "File": "File", 
            "Format": "Format", 
            "Free": "Free", 
            "Freq": "Freq", 
            "Frequency": "Frequency", 
            "Front": "Front", 
            "Func": "Func", 
            "G": "G", 
            "G+": "G+", 
            "G-": "G-", 
            "GHz": "GHz", 
            "GND": "GND", 
            "GO": "GO", 
            "Gnd": "Gnd", 
            "HI": "HI", 
            "H_line": "H line", 
            "Help": "Help", 
            "Hexagon": "Hexagon", 
            "Hz": "Hz", 
            "I": "I", 
            "IN": "IN", 
            "IN+": "IN+", 
            "IN-": "IN-", 
            "I_Input": "I Input", 
            "In/Out": "In/Out", 
            "Input": "Input", 
            "Instrument_State": "Instrument State", 
            "Int": "Int", 
            "J": "J", 
            "K": "K", 
            "LO": "LO", 
            "Label": "Label", 
            "Legend": "Legend", 
            "Line": "Line", 
            "Line_On/Off": "Line On/Off", 
            "Load": "Load", 
            "Loading": "Loading", 
            "Local": "Local", 
            "M": "M", 
            "MHz": "MHz", 
            "Man": "Man", 
            "Mark": "Mark", 
            "Marker": "Marker", 
            "Math": "Math", 
            "Max": "Max", 
            "Mea-": "Mea-", 
            "Meas": "Meas", 
            "Menu": "Menu", 
            "Min": "Min", 
            "Mode": "Mode", 
            "Network": "Network", 
            "Next": "Next", 
            "Null": "Null", 
            "OE": "OE", 
            "OUT": "OUT", 
            "Off": "Off", 
            "Offset": "Offset", 
            "On": "On", 
            "On/Off": "On/Off", 
            "Opt_1": "Opt 1", 
            "Opt_2": "Opt 2", 
            "Opt_3": "Opt 3", 
            "Opt_4": "Opt 4", 
            "Oscilloscope": "Oscilloscope", 
            "Output": "Output", 
            "PW": "PW", 
            "Pattern": "Pattern", 
            "Peak": "Peak", 
            "Period": "Period", 
            "Port_1": "Port 1", 
            "Port_2": "Port 2", 
            "Power": "Power", 
            "Preset": "Preset", 
            "Print": "Print", 
            "Pulse": "Pulse", 
            "Q": "Q", 
            "Q_Input": "Q Input", 
            "R": "R", 
            "R1": "R1", 
            "R2": "R2", 
            "RF": "RF", 
            "RF_COUNTER": "RF COUNTER", 
            "R_Channel": "R Channel", 
            "Range": "Range", 
            "Rear": "Rear", 
            "Recall": "Recall", 
            "Rectangle": "Rectangle", 
            "Ref": "Ref", 
            "Restart": "Restart", 
            "Return": "Return", 
            "Rhombus": "Rhombus", 
            "Rounded Rectangle": "Rounded Rectangle", 
            "Run": "Run", 
            "S": "S", 
            "SCL": "SCL", 
            "SCLK": "SCLK", 
            "SDA": "SDA", 
            "SDATA": "SDATA", 
            "SEL0": "SEL0", 
            "SEL1": "SEL1", 
            "SEL2": "SEL2", 
            "SEL3": "SEL3", 
            "Save": "Save", 
            "Save/": "Save/", 
            "Saw": "Saw", 
            "Scale/": "Scale/", 
            "Search": "Search", 
            "Seq": "Seq", 
            "Setup": "Setup", 
            "Shift": "Shift", 
            "Single": "Single", 
            "Source": "Source", 
            "Span": "Span", 
            "Spectrum": "Spectrum", 
            "Sq": "Sq", 
            "Start": "Start", 
            "Stimulus": "Stimulus", 
            "Stop": "Stop", 
            "Sweep": "Sweep", 
            "System": "System", 
            "T": "T", 
            "Time": "Time", 
            "Trace": "Trace", 
            "TrackC": "TrackC", 
            "Transient Analysis": "Transient Analysis", 
            "Tri": "Tri", 
            "Triangle": "Triangle", 
            "Trig": "Trig", 
            "Trigger": "Trigger", 
            "V": "V", 
            "V+": "V+", 
            "V-": "V-", 
            "V-sweep": "V-sweep", 
            "VDD": "VDD", 
            "VREF": "VREF", 
            "VSS": "VSS", 
            "V_Line": "V Line", 
            "Vaa": "Vaa", 
            "Vbb": "Vbb", 
            "Vcc": "Vcc", 
            "Vdd": "Vdd", 
            "Vee": "Vee", 
            "Video": "Video", 
            "Vin": "Vin", 
            "Volume": "Volume", 
            "Vss": "Vss", 
            "W": "W", 
            "W1": "W1", 
            "W2": "W2", 
            "Y": "Y", 
            "Zoom": "Zoom", 
            "ac": "AC Value", 
            "ac simulation": "ac simulation", 
            "ac_voltage": "AC Voltage", 
            "alert": "Alert", 
            "alert_login_digikey_proj": "You must log into your Digikey account. The state of your current project has been saved to your browser session.", 
            "alert_projname": "You must give the project a name.", 
            "alert_select_category": "Please select at least one category", 
            "alertcantstartsim_circuit": "Cannot start simulator without a circuit.", 
            "alertdeletefrom_projpanel": "Delete must be done from project panel!", 
            "alertdroppinon_customsymbol": "You must drop the pin onto a custom symbol.", 
            "alertfuncnotimplemented": "Sorry, this function is not implemented yet.", 
            "alertgiveprojname": "You must give the project a name.", 
            "alertgroupnot_rotate": "Sorry, but groups cannot be rotated.", 
            "alertgroupscantflip": "Sorry, but groups cannot be flipped.", 
            "alertmessage_fail": "Share message send failed.", 
            "alertmessage_sent": "Share message Sent", 
            "alertmessage_xls": "This will download your BOM to an excel spreadsheet. You can upload this file to the", 
            "alertmessage_xls_bom": "Digi-Key BOM Manager", 
            "alertmessage_xls_quote": "to create a quote for the parts listed.", 
            "alertnoaccesstoproj": "You do not have access to this project.", 
            "alertnotauthorizedtoview": "You are not authorized to view this simulation.", 
            "alertoverride": "You must override this function!", 
            "alertoverride_must": "eeProject.restoreProject must be overidden.", 
            "alertsavecheck_notsupported": "Save Check is no longer supported!", 
            "alertsavesession_notsupported": "Save Session is no longer supported!", 
            "alertselectprojtoopen": "You must select a project to open.", 
            "alertsharenotsupported.revision": "Share is not supported on this revision!", 
            "alertunablesaveproj": "We were unable to save your project. Please try again. If you continue to get this error, please report it.", 
            "alertunabletoretrieve_proj": "Sorry, but we were unable to retrieve a list of projects for you.", 
            "alertungroupselect_grouponly": "In order to ungroup you must select the group only.", 
            "alertvalid_email": "You must enter a valid email address.", 
            "allchanges_lost": "All changes will be lost!", 
            "allchangeslost": "All changes will be lost!", 
            "amperes": "Amperes", 
            "amps": "Amps", 
            "area_drain_diffusion": "Area of Drain Diffusion", 
            "area_scale_factor": "Area Scale Factor", 
            "area_source_diffusion": "Area of Source Diffusion", 
            "base_area_factor": "Base Area Factor", 
            "bom_assemblies": "BOM Assemblies", 
            "bom_assembly_number_ok": "Submit", 
            "bom_confirm_dlg_title": "Import a BOM File", 
            "bom_order_options": "Order Options", 
            "bom_please_specify_number_of_assemblies": "Please specify the number of assemblies you plan to create from this BOM order.", 
            "bom_select_dlg_body": "Sheet Name", 
            "bom_select_dlg_title": "Select a worksheet", 
            "browse": "browse", 
            "cancel": "Cancel", 
            "cancelled": "cancelled", 
            "cantdelete_proj": "You cannot delete the current project!", 
            "capacitance": "Capacitance", 
            "capacitance_length": "Capacitance / Length", 
            "categories": "Categories", 
            "category_import_bom": "Import BOM", 
            "channel_l": "Channel Length", 
            "channel_w": "Channel Width", 
            "characteristic_impedance": "Characteristic Impedance", 
            "chart_dl_csv": "Download CSV document", 
            "chart_dl_jpg": "Download JPEG image", 
            "chart_dl_pdf": "Download PDF document", 
            "chart_dl_png": "Download PNG image", 
            "chart_dl_svg": "Download SVG vector image", 
            "chart_dl_text": "Download TEXT document", 
            "chart_dl_xls": "Download XLS document", 
            "check_project_name": "Checking for existing projects", 
            "chooseacolor": "Choose a Color", 
            "circuit": "Circuit", 
            "clear_all": "Clear All", 
            "clearing": "Clearing", 
            "click_projname_to_open": "Click on project name to open project.", 
            "close": "Close", 
            "collector_area_factor": "Collector Area Factor", 
            "complete": "Complete", 
            "component_name": "Name", 
            "component_preview": "Component Preview", 
            "component_shortcuts": "Component Shortcuts", 
            "component_value": "Value", 
            "componentproperties": "Component Properties", 
            "componentproperties_cancel": "Cancel", 
            "componentproperties_save": "Save", 
            "conductance_length": "Conductance / Length", 
            "confirm_download_template": "Download Template", 
            "confirm_example_format": "Example Format", 
            "confirm_proceeddelete": "Select CONFIRM to proceed with the deletion.", 
            "confirm_select_import": "Select \"Import\" to import an Excel File that is in the Digi-Key format", 
            "confirmation": "Confirmation", 
            "confirmation_ok": "Ok", 
            "contact_page": "Contact Page", 
            "controlledsource": "Controlled Source", 
            "copy": "Copy", 
            "coupling_coefficient": "Coefficient of Coupling", 
            "create": "Create", 
            "create_new_model": "Create New Model", 
            "create_new_model_instruction": "Paste text for spice model/s in the area below", 
            "current": "Current", 
            "current_gain": "Current Gain", 
            "currentnetlist": "Current Netlist", 
            "cursor_button_tooltip_A": "click to set cursor A for", 
            "cursor_button_tooltip_B": "click to set cursor B for", 
            "cursor_clear_tooltip_A": "click to clear cursor A for", 
            "cursor_clear_tooltip_B": "click to clear cursor B for", 
            "cut": "Cut", 
            "dblclick_page_name": "Doubleclick to edit...(Max 15 chars.)", 
            "dc simulation": "dc simulation", 
            "dc_current": "DC Current", 
            "dc_voltage": "DC Voltage", 
            "default_alert": "Alert!", 
            "default_ok": "Ok", 
            "default_page_name": "Page", 
            "default_spice_models": "Default Spice Models", 
            "degrees": "Degrees", 
            "delete": "Delete", 
            "delete_page": "Delete Page", 
            "delete_pagenotempty": "You are about to delete a page that is not empty.", 
            "description": "Description", 
            "dialog simulation": "dialog simulation", 
            "digikey": "Digi-Key", 
            "digikey_catalog_drawings": "Catalog Drawings", 
            "digikey_partnum": "Digi-Key Part Number", 
            "digikey_product_datasheet": "Datasheet", 
            "digikey_product_photos": "Product Photos", 
            "digikey_product_viewdatasheet": "View Datasheet", 
            "digikeysearch": "Digikey Search", 
            "dkpartnumber": "Digi-Key Part Number", 
            "dksearch": "Digikey Search", 
            "dont_have_account": "Don't have an account?", 
            "dont_have_account_partsim": "Don't have an account?", 
            "downloadbom": "Download BOM", 
            "downloadbom_cancel": "Cancel", 
            "downloadbom_download": "Download", 
            "drag_to_create_component": "Drag image to create a component.", 
            "drag_to_symbol_to_assign": "Drag to Symbol to Assign", 
            "dtemp": "Difference Temperature", 
            "duplicate_project_name": "Project name is duplicate", 
            "duplicate_refdes": "This reference designator already exists. Please provide a different one.", 
            "edit_link": "Edit Link", 
            "edit_page_name": "Edit Page Name", 
            "editproperties": "Edit Properties", 
            "embed_bill_of_materials": "Bill of Materials", 
            "embed_unnamed_project": "Unnamed Project", 
            "embedded_noload": "Embedded Client cannot be loaded.", 
            "embedded_winsize": "Minimum window size is 400x300. Current size is", 
            "emitter_area_factor": "Emitter Area Factor", 
            "empty_component_description": "The server didn't return any results.", 
            "empty_component_title": "No Results", 
            "enable_dc_current": "Enable DC Current", 
            "enable_dc_voltage": "Enable DC Voltage", 
            "enter_valid_image_url": "Enter a valid URL ( .png, .jpg, .jpeg )", 
            "error": "Error", 
            "error_bom_assembly_number": "Must be a number greater than 0", 
            "error_component_description": "The server encountered an error.", 
            "error_component_title": "Server Error", 
            "error_no_partnumber": "There are no components with __vendorTitle__ part number.", 
            "error_ok": "Ok", 
            "error_title_no_vendor_parts": "Error: No Vendor Parts", 
            "errornoparts_number": "There are no components with a Digi-Key part number.", 
            "errornoparts_number_ok": "Ok", 
            "errornoparts_order": "Error: no parts to order", 
            "expectedaninteger": "Expected an Integer", 
            "expectedfloatingpointnumber": "Expected a floating point number.", 
            "export_all": "Export all", 
            "export_filename": "schemeit-project", 
            "export_pngext": ".png", 
            "exportcurrent_page": "Export Current Page", 
            "exportcurrent_page_cancel": "Cancel", 
            "exportcurrent_page_export": "Export", 
            "exported_bom": "exported-bom", 
            "farads": "Farads", 
            "feedback_cancel": "Cancel", 
            "feedback_no_email": "Note: We will not be able to respond to your feedback if you do not include a reply email address.", 
            "feedback_ok": "Ok", 
            "feedback_send": "Send", 
            "fieldisrequired": "Field is required.", 
            "fliphorizontally": "Flip Horizontally", 
            "flipvertically": "Flip Vertically", 
            "frequency": "Frequency", 
            "frequency_with_electrical_length": "Frequency is needed together with normalized electrical length", 
            "general_shortcuts": "General Shortcuts", 
            "generating_sprite": "Generating sprite", 
            "go": "Go", 
            "grouping_disabled": "Grouping has been disabled to avoid netlist corruption.", 
            "header_project": "Projects:", 
            "henrys": "Henrys", 
            "hertz": "Hertz", 
            "hide_grid": "Hide Grid", 
            "hide_model_text": "Hide Model Text", 
            "hiding": "Hiding", 
            "hysteresis_current": "Hysteresis Current", 
            "hysteresis_voltage": "Hysteresis Voltage", 
            "ic": "Initial Condition", 
            "image": "Image", 
            "import_bom_assign_symbol": "Assign Symbol", 
            "import_bom_delete_import": "Delete this BOM Import", 
            "import_bom_delete_part": "Delete Part", 
            "import_bom_dlg_error_msg": "No selected part", 
            "import_bom_dlg_error_title": "Select a part", 
            "import_bom_dlg_note": "Note: Click a cell under the name column to edit a name", 
            "import_bom_dlg_title": "Select Parts to Import", 
            "import_bom_import_desc": "After import, right-click on a part for options.", 
            "import_bom_import_title": "Click to Import.", 
            "import_bom_login_desc": "Log into your Digi-Key account to import.", 
            "import_bom_login_title": "Login", 
            "import_bom_remove_symbol": "Remove Symbol", 
            "import_name_exist": "Import Name already exists", 
            "include_in_bom": "Include in BOM", 
            "include_in_bom_tip": "Indicates if this component is included in BOM.", 
            "index": "Index", 
            "inductance": "Inductance", 
            "inductance_length": "Inductance / Length", 
            "inductor_1_value": "Inductor 1 Value", 
            "inductor_2_value": "Inductor 2 Value", 
            "initializingapp": "Initializing application...", 
            "install_chrome_frame": "Install Chrome Frame", 
            "invalid_characters": "Invalid characters after number. ( __characters__ )", 
            "invalid_characters_found": "Invalid characters found.", 
            "invalid_characters_mustbe": "Must be one of __valid_multiplier__ , Optionally followed by units: __valid_units__ .", 
            "invalid_email": "Invalid email.", 
            "invalid_image_url": "Invalid image url", 
            "invalid_model_line \"__modelLine__\" ( at_line __lineIndex__ )": "Invalid model line \"__modelLine__\" ( at line __lineIndex__ )", 
            "invalid_multiplier": "Invalid multiplier ( __multiplier__ ).", 
            "invalid_multiplier_mustbe": "Must be one of __valid_multiplier__ .", 
            "invalid_name": "Invalid name.", 
            "invalid_units": "Invalid units ( __units__ ).", 
            "invalid_units_mustbe": "Must be one of __valid_units__ .", 
            "kHz": "kHz", 
            "keyboard_shortcuts": "Keyboard Shortcuts", 
            "legend_info": "Legend Info", 
            "length": "Length", 
            "length_line": "Length of Line", 
            "link": "Link", 
            "local_login": "Username:", 
            "login": "Login", 
            "login_button": "Login", 
            "login_cancel_button": "Cancel", 
            "login_email": "Email Address:", 
            "login_error": "We can't verify your login data. Please check if your login information is correct.", 
            "login_error_title": "Login Error", 
            "login_partsim_email": "Email Address:", 
            "login_partsim_password": "Password:", 
            "login_partsim_register": "Register Here", 
            "login_password": "Password:", 
            "login_register": "Register Here", 
            "login_username": "Username", 
            "logout": "Logout", 
            "lumps": "Lumps", 
            "m": "Multiplier", 
            "magnitude_plot": "Magnitude Plot", 
            "manpn": "Part Number", 
            "manu": "Manufacturer", 
            "manufacturer_name": "Manufacturer", 
            "manufacturer_partnum": "Manufacturer Part Number", 
            "manufacturer_partnumber": "Manufacturer Part Number", 
            "max_point_transient_max": "The maximum number of points in a Transient sweep is __limit__ .  The specified step size could result in as many as __nPtsMax__ points.  Please reduce the total number of points in the sweep and try again.  The number of points is calculated from (Stop-Start)/Step.", 
            "max_points_ac": "The maximum number of points in a AC sweep is __max__ .  You have specified a sweep of __nPts__ .  Please reduce the total number of points in the sweep and try again", 
            "max_points_dc": "The maximum number of points in a DC sweep is __max__ .  You have specified a sweep of __ndcPoints__ .  Please reduce the total number of points in the sweep and try again.  The number of points is calculated from (Stop-Start)/Step.", 
            "max_points_transient_min": "The maximum number of points in a Transient sweep is __limit__ .  You have specified a sweep of __nPtsMin__ .  Please reduce the total number of points in the sweep and try again.  The number of points is calculated from (Stop-Start)/Max Step.", 
            "meter": "meter", 
            "model_editor": "Model Editor", 
            "model_not_parsed_no_results": "Model was not parsed properly. No results.", 
            "modelname": "Spice Model", 
            "must_login": "You must log into your account.", 
            "must_login_partsim": "You must log into your Partsim account.", 
            "must_login_simit": "You must log into your SimIt account.", 
            "my_project": "my-project", 
            "name": "Name", 
            "name_of_import": "Name of Import", 
            "netlist_noeffect": "Edits to the netlist have no effect. Feel free to copy the netlist, but you must modify the circuit elements to alter the simulation.", 
            "new_model": "New Model", 
            "newproject": "New Project", 
            "no_data_in_table": "No data available in table", 
            "no_data_to_display": "No data to display", 
            "no_description": "No description provided", 
            "no_image_found": "No image found with that url", 
            "no_match_records": "No matching records found", 
            "no_matching_digikey": "No matching products found.", 
            "no_summary": "No summary provided", 
            "nocomponent_selected": "No component selected.", 
            "nogroundnet_found": "No ground net was found. Please connect a ground symbol, found under \"Ports\", to the net that represents the circuit ground", 
            "noisy": "Noisy", 
            "noprobes_spec": "No Probes specified, and there are too many nets to probe them all (> 20). Simulation Cancelled.", 
            "noproj_open": "There were no projects saved under your username.  If you feel this message is an error, please notify us using Feedback.", 
            "noprojunderusername": "There were no projects saved under your username.  If you feel this message is an error, please notify us.", 
            "noresultscheck_log": "No Results returned. Please check output log.", 
            "normalized_length": "Normalized Electrical Length", 
            "not_empty": "Can't be empty.", 
            "notes": "Notes", 
            "notes_dialog_tab_description": "Description", 
            "notes_dialog_tab_summary": "Summary", 
            "nounitsormultiallowed_floatvalue": "No units or multiplier allowed on float value.", 
            "nrd": "Number of Squares of the Drain Diffusion", 
            "nrs": "Number of Squares of the Source Diffusion", 
            "nt": "Number of Turns", 
            "off_resistance": "Off Resistance", 
            "ohm": "Ohm", 
            "ohms": "Ohms", 
            "on_resistance": "On Resistance", 
            "onsavemod_cancel": "Cancel", 
            "onsavemod_dialog": "Do you want to save the changes you made in the current project?", 
            "onsavemod_dont_save": "Don't Save", 
            "onsavemod_save": "Save", 
            "onsavemod_title": "Save Current Project?", 
            "open_next_proj": "Open Next Project", 
            "open_prev_proj": "Open Previous Project", 
            "openproj": "Open Project", 
            "openproj_cancel": "Cancel", 
            "openproj_delete": "Delete", 
            "openproj_open": "Open", 
            "openproject": "Open Project", 
            "param_boolean_enabled": "Enabled", 
            "param_on_off": "On/Off", 
            "parser_error_message": "There is an error in the project data and we are unable to save the project. The development team has been notified of this issue.\n<br><br>\nFor now, we recommend you undo recent changes or remove any special characters pasted to text that may have caused the error.\n<br><br>\nIf this is an existing project, you may also reload the project but you will lose any changes.", 
            "partnumber": "Part Number", 
            "partsim_com": "PartSim.com", 
            "partsim_simulation_client": "PartSim Simulation Client", 
            "paste": "Paste", 
            "perimeter_drain": "Perimeter of Drain Junction", 
            "perimeter_scale_factor": "Perimeter Scale Factor", 
            "perimeter_source": "Perimeter of Source Junction", 
            "phase_plot": "Phase Plot", 
            "print_chart": "Print chart", 
            "print_export_chart": "Print/Export Chart", 
            "print_preview_setup": "Print Preview Setup", 
            "proceed": "Proceed", 
            "product_datasheet": "Product Datasheet", 
            "product_datasheet_title": "View Datasheet", 
            "product_photo": "Product Photo", 
            "proj_name_duplicate": "Project name is duplicate", 
            "project": "project", 
            "project_exists": "A project __name__ already exists. Do you want to replace it?", 
            "project_exists_cancel": "Cancel", 
            "project_exists_replace": "Replace", 
            "project_is_modified": "Project is modified.", 
            "project_models": "Project Models", 
            "project_name_too_long": "The project name is too long.", 
            "project_shortcuts": "Project Shortcuts", 
            "projispublic": "Project is public:", 
            "projname": "Project Name:", 
            "properties": "Properties", 
            "properties_table_attribute": "Attribute", 
            "properties_table_description": "Description:", 
            "queued": "queued", 
            "radians": "Radians", 
            "redo": "Redo", 
            "ref_des": "Reference Designator", 
            "refdes": "RefDes", 
            "refdes_invalid": "Reference designator invalid. Example: __prefix__1 .", 
            "refdes_invalid_format": "Reference designator invalid format. Should not contain spaces or special characters.", 
            "refdes_prefix_invalid": "Invalid Refdes prefix. Should be __prefix__ .", 
            "refdes_prefix_invalid_character": "Invalid character for Refdes prefix.", 
            "references": "References", 
            "renew_access_token": "Sent a request to renew your access. Please try again.", 
            "reorder_pin_instruction": "Reorder pins according to the model input order. Watch how", 
            "request_quote": "Request Quote", 
            "reset_zoom": "Reset zoom", 
            "reset_zoom_tooltip": "Reset zoom level 1:1", 
            "resistance": "Resistance", 
            "resistance_length": "Resistance / Length", 
            "restore_project_session": "Restore Project Session", 
            "restore_project_session_msg": "Do you want to restore the previous changes you made in the current project?", 
            "rotate": "Rotate", 
            "running": "running", 
            "runsimulation": "Run Simulation", 
            "runsimulation_cancel": "Cancel", 
            "runsimulation_run": "Run", 
            "save": "Save", 
            "save_update": "Save and Update", 
            "saveasproj_overwrite": "Overwrite Existing Project?", 
            "saveproject": "Save Project", 
            "saveshareproj_dlg_dont_save": "Don't Save", 
            "saveshareproj_dlg_save": "Save", 
            "saveshareproj_save": "You must save the project before it can be shared. Save now?", 
            "scale": "Scale", 
            "schematic_help": "Schematics Help", 
            "schematics_com_feedback": "SCHEMATICS.COM Feedback", 
            "schemeit_help": "Scheme-it Help", 
            "schemeit_line_style": "Line Style", 
            "schemeitfeedback": "Scheme-it Feedback", 
            "schemeitfeedback_entermsg": "You must enter text in the message body.", 
            "schemeitterms": "Scheme-it Terms & Conditions", 
            "schemeitterms_agree": "I Agree", 
            "schemeitterms_cancel": "Cancel", 
            "schemeitterms_close": "Close", 
            "search_box_partsearch": "Search Parts", 
            "search_box_partsearch_old": "Search Parts", 
            "searchbar_input_label": "Search Parts", 
            "searching_digikey": "Searching...", 
            "searching_vendor": "Searching...", 
            "seconds": "Seconds", 
            "select_all": "Select All", 
            "select_model": "Select a model", 
            "select_series_with_unit": "Select a series with a y-axis unit", 
            "select_spice_model": "Select Spice Model", 
            "selectedcomponent_noprop": "Selection component has no properties.", 
            "selectionnot_component": "Selection is not a component.", 
            "selectproj_delete": "You must select a project to delete.", 
            "selectproj_open": "You must select a project to open.", 
            "send_feedback": "Send us a feedback with your comments by clicking here.", 
            "setnetname": "Set Net Name", 
            "shareproj": "Share Project", 
            "shareproject": "Share Project", 
            "sharesaveproj": "Save Current Project?", 
            "sharevia_email": "Share via Email", 
            "shift_enter_newline": "Use Shift+Enter for new line.", 
            "show_grid": "Show Grid", 
            "show_hide_legend_info": "Show or Hide Legend Info", 
            "show_model_text": "Show Model Text", 
            "show_retrieved_parts": "Showing __count__ parts.", 
            "showing": "Showing", 
            "sidebar_diagramming": "Diagramming", 
            "sidebar_generic_parts": "Generic Parts", 
            "sidebar_loading": "Loading", 
            "sidebar_vendor_parts": "Vendor Parts", 
            "sim_queue_full": "The simulation queue is full.  Please try again after a few moments.  If this situation persists, then we will work to add more simulation resources.  Please", 
            "sim_queue_full_contact": "contact us", 
            "sim_queue_full_questions": "if you have additional questions.", 
            "sim_ran_too_long": "Your simulation ran for too long and was cancelled. Please reduce the length of your simulation by using fewer steps. If the total number of simulation steps is not too high, the simulator may have failed to converge on a solution. Check your model parameters, and if you are still unable to resolve the issue, send a message to support@eeweb.com", 
            "simcomplete_seeresults": "Simulation completed. See results tabs for data.", 
            "simulation": "Simulation", 
            "simulation_time": "Simulation Time", 
            "spice_errormessage": "Unfortunately, we have experienced an error with your simulation.  We have been informed of this error, and will look into a solution.", 
            "spice_model_manager": "Spice Model Manager", 
            "spice_model_text": "Spice Model Text", 
            "start_import": "Import", 
            "submit": "Submit", 
            "submit_quote_request": "Submit", 
            "super_source": "Super Source", 
            "sure": "sure", 
            "tags": "Tags", 
            "temp": "Temperature", 
            "temp_is_max": "Maximum temperature value is __maxval__", 
            "temp_is_min": "Minimum temperature value is __minval__", 
            "tempmustbefloatingpoint": "Temperature must be a floating point number.", 
            "temptoolong_mustbecorf": "Temperature units too long. If supplied, the unit must be C or F.", 
            "tempunitsmustbe_corforblank": "Temperature units must one C or F or blank.", 
            "this_is_a_test": "This is a test of an internal %hostname% replaceable %password% string type.", 
            "threshold_current": "Threshold Current", 
            "threshold_voltage": "Threshold Voltage", 
            "time": "Time", 
            "tip": "Tip", 
            "title": "Title", 
            "to_copy_text": "to Copy Text", 
            "tool_body_automotive": "AUTOMOTIVE", 
            "tool_body_basic_shapes": "Basic Shapes", 
            "tool_body_custom_sym": "Custom Symbols", 
            "tool_body_interface": "INTERFACE/CONN.", 
            "tool_body_logic": "LOGIC", 
            "tool_body_schematic_sym": "Schematic Symbols", 
            "tool_body_symbols": "Diagram Symbols", 
            "tool_body_system_blocks": "SYSTEM BLOCKS", 
            "tool_body_system_icons": "SYSTEM ICONS", 
            "tool_body_system_level": "System Level", 
            "toolbar_group_group": "Group", 
            "toolbar_group_ungroup": "UnGroup", 
            "total_points": "total points", 
            "total_points_per_decade": "total points per decade", 
            "total_points_per_octave": "total points per octave", 
            "transconductance": "Transconductance", 
            "transient_voltage": "Transient Voltage", 
            "transmission_delay": "Transmission Delay", 
            "transresistance": "Transresistance", 
            "typedelete_proj": "Type 'DELETE' in the box below to confirm that you really want to delete this project. This operation is irreversible.", 
            "undo": "Undo", 
            "unnamed_project": "Unnamed Project", 
            "unsaved_small_caps": "(unsaved)", 
            "unsupported_browser": "Unsupported Browser", 
            "unsupportedbrowser": "Unsupported Browser", 
            "updating": "Updating", 
            "upgrade_browser": "Upgrade Browser", 
            "user_spice_models": "User Spice Models", 
            "username": "Username", 
            "value": "Value", 
            "value_is_max": "Maximum value is __maxval__", 
            "value_is_min": "Minimum value is __minval__", 
            "value_mustbe_max": "Value must be less than or equal to __maxval__ .", 
            "value_mustbe_min": "Value must be greater than or equal to __minval__ .", 
            "value_not_valid": "Value is not a valid __value__ .", 
            "vendor": "Vendor", 
            "vendor_partnumber": "__vendor__ Part Number", 
            "vendor_search": "__vendor__ Search", 
            "vendor_search_assign": "Assign", 
            "vendor_search_close": "Close", 
            "view_more_digikey": "View More at Digi-Key", 
            "voltage": "Voltage", 
            "voltage_gain": "Voltage Gain", 
            "volts": "Volts", 
            "warning_empty_keywords": "Please provide keywords before sending.", 
            "welcomeguest": "Welcome Guest", 
            "welcometoschemeit": "Welcome to Scheme-it", 
            "welcometoschemeit_login": "Register/Login", 
            "welcometoschemeit_tryit": "Try It Now", 
            "work_will_not_be_saved": "(work will not be saved)", 
            "x10": "x10", 
            "zoom_fit": "Zoom to Fit", 
            "zoom_in": "Zoom In", 
            "zoom_out": "Zoom Out"
        }
    }
};
