document.write ('<!-- BEGIN JS TAG - commentcamarche.net hightech atf - Forum Mban ATF  < - DO NOT MODIFY --><div id="asq_top"><center><script type="text/javascript">document.write(');
document.write ("'");
document.write ('<script src="http://ib.adnxs.com/ttj?id=1201484&size=1000x300&promo_sizes=970x250,1000x90,970x90,728x90&promo_alignment=center&referrer=commentcamarche.net&cb=802923297&pt1=http://ba.commentcamarche.net/3/fr_ccm_hightech/forum/L21/L21/802923297@Top?RM_Exclude=ASQ" type="text/javascript"><');
document.write ("'");
document.write ('+');
document.write ("'");
document.write ('/script>');
document.write ("'");
document.write (');</script></center></div><script>if((document.getElementById(');
document.write ("'");
document.write ('asq_top');
document.write ("'");
document.write (').offsetWidth)>728){document.write(');
document.write ("'");
document.write ('<style type="text/css">#ba_top1{display:none}</style>');
document.write ("'");
document.write (');}</script><!-- END TAG -->');
